### ISSUE TITLE
Autocompletion incorrectly prefixes suggestions with xsi namespace

### ISSUE THREAD

**Issue by felixfbecker** [angelozerr/lsp4xml#116]
I have a document that must not use namespaces (ps1xml files). I get completion, but they are always prefixed with `xsi` (from the `xsi` namespace declaration)

![image](https://user-images.githubusercontent.com/10532611/45354583-3c025680-b5be-11e8-8ef9-639b20cce1ff.png)

```xml
<Configuration xsi:noNamespaceSchemaLocation="Format.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
```

Am I missing something?

**Comment by fbricon** [comment]
Can you please attach your xsd?

**Comment by felixfbecker** [comment]
Yep, it's here: https://github.com/felixfbecker/PowerShellXSD

(I am still learning XSD so it may be that something is wrong with it)

**Comment by felixfbecker** [comment]
Okay, so there was a bug in my schema which I fixed now. There was not "invalid schema" message btw at the schema instance, only when opening the schema.

So I now do get the right completion entries, but it _also_ still adds all these prefixed entries which are wrong (they don't belong to that namespace, and they are not valid in the context even without the prefix)

![image](https://user-images.githubusercontent.com/10532611/45371506-16d80d00-b5eb-11e8-8371-cbef4d79fac2.png)

**Comment by angelozerr** [comment]
It's a bug. I'm reading namespace spec to fix it.

**Comment by angelozerr** [comment]
It should be fixed. @felixfbecker please give us feedback.

**Comment by felixfbecker** [comment]
Tried with build 209 of vscode-xml and it's still happening. Did you try it on the project I linked above?

**Comment by angelozerr** [comment]
lsp4xml build was failling. I have fixed the problem now.

**Comment by felixfbecker** [comment]
Fixed, thanks!

**Comment by angelozerr** [comment]
You are welcome:)
