### ISSUE TITLE
Adjust range for XML schema errors

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#72]

**Comment by fbricon** [comment]
@angelozerr what's the status on this one?

**Comment by angelozerr** [comment]
Thanks for the info @fbricon I will try to improve this range problem.

**Comment by angelozerr** [comment]
@fbricon I have managed selection of error date, but I have not written test. Do you think we can use the IBM Language Server invoice.xsd to write test?

**Comment by fbricon** [comment]
I guess you can. Project is EPL. In doubt you can easily create a simple schema with dates

**Comment by fbricon** [comment]
So we made some progress but I still see bad ranges at the end of problematic nodes:
<img width="540" alt="screen shot 2018-09-22 at 2 15 35 am" src="https://user-images.githubusercontent.com/148698/45914067-80d38c00-be0d-11e8-90de-19c55618605e.png">

**Comment by angelozerr** [comment]
> I guess you can. Project is EPL. In doubt you can easily create a simple schema with dates

Ok thanks, I will create a new file for that according your suggestion

> So we made some progress but I still see bad ranges at the end of problematic nodes:

Yes I know that, the error is for `cvc-datatype-valid.1.2.1` (I seems that the Xerces version of IBM Language server doesn't manage it).

The sample at https://wiki.xmldation.com/Support/Validator/cvc-datatype-valid-1-2-1 is for element text, but I tell me if for attribute value we can have this error too? I had implemented that in https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/contentmodel/participants/XMLSchemaErrorCode.java#L120 (but it's commented). I would like to check if we can hav ethis error for attribute value. Once I will check it, I will write tests for that.

**Comment by angelozerr** [comment]
@fbricon now we should have the same thing than IBM XML Language Server.

**Comment by fbricon** [comment]
Still seeing bad ranges for invalid attributes content (closing bracket is underlined):
<img width="546" alt="screen shot 2018-09-22 at 7 11 50 pm" src="https://user-images.githubusercontent.com/148698/45922517-b8891500-be9b-11e8-917a-2d028ac8fab5.png">

**Comment by angelozerr** [comment]
Now it should be better.

**Comment by fbricon** [comment]
Nope. Still seeing underline on closing bracket. Range is still wrong:
<img width="1039" alt="screen shot 2018-09-23 at 11 49 01 pm" src="https://user-images.githubusercontent.com/148698/45937112-4d1e7080-bf8b-11e8-82ba-f49634e98860.png">

**Comment by angelozerr** [comment]
> Nope. Still seeing underline on closing bracket. Range is still wrong:

Are you sure that you are using version from master? Test are https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/test/java/org/eclipse/lsp4xml/contentmodel/XMLSchemaDiagnosticsTest.java#L136

**Comment by fbricon** [comment]
yes, that's why I made https://github.com/angelozerr/lsp4xml/pull/139, to be sure about the version running

**Comment by angelozerr** [comment]
Sorry @fbricon there were indeed a bug that it should be fixed. Sorry again -(

**Comment by fbricon** [comment]
Works now! Thanks @angelozerr !
Are we still missing anything to close this issue?

**Comment by fbricon** [comment]
Fair enough. closing

**Comment by angelozerr** [comment]
@fbricon just for your information, I have played with the XML IBM XML Server and I have fixed few problems with completions and improve code actions.

Here the code actions which is avalable:

![image](https://user-images.githubusercontent.com/1932211/45960409-789d6b80-c01c-11e8-822d-66e828564a9b.png)

![image](https://user-images.githubusercontent.com/1932211/45960442-8a7f0e80-c01c-11e8-8dd1-3036599936d3.png)

![image](https://user-images.githubusercontent.com/1932211/45960474-9cf94800-c01c-11e8-9a6b-2968ba7e2405.png)

and here completion for attribute name:

![image](https://user-images.githubusercontent.com/1932211/45960534-bbf7da00-c01c-11e8-89fc-e7ec0d5ff5de.png)

and for attribute value:

![image](https://user-images.githubusercontent.com/1932211/45960590-d467f480-c01c-11e8-967f-32f7b0b69dc7.png)

The completion on attribute value is bugged when you fill the value, apply value is not well done.
